name: 'AutoMerger'
description: 'Auto merge a branch on PR close'
inputs:
  token:
    description: 'Github token'
    required: true
  base:
    description: 'Source branch'
    required: true
  head:
    description: 'Target branch'
    required: true
  label:
    description: 'Required label to enable merge'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
