on:
  pull_request:
    types:
      - closed
      - open

jobs:
  auto_merge_job:
    runs-on: ubuntu-latest
    name: AutoMerge to UAT
    steps:
      - name: AutoMerge merge step
        id: AutoMerge
        uses: drnare/auto-merge@v1.0
        with:
          base: develop
          head: uat
          label: auto-merge-to-uat
