on:
  pull_request:
    types:
      - closed

jobs:
  auto_merge_job:
    runs-on: ubuntu-latest
    name: Auto Merge to UAT
    steps:
      - name: Auto Merge merge step
        id: AutoMerge
        uses: drnare/auto-merge@v1.0
        with:
          source: main
          target: uat
          label: auto-merge-to-uat
          token: ${{ secrets.GITHUB_TOKEN }}
