on:
  pull_request:
    types:
      - closed
      - open

jobs:
  auto_merge_job:
    runs-on: ubuntu-latest
    name: AutoMerge to UAT
    steps:
      - name: AutoMerge merge step
        id: AutoMerge
        uses: drnare/auto-merge@v1.0
        with:
          source: develop
          target: uat
          label: auto-merge-to-uat
          token: ${{ secrets.GITHUB_TOKEN }}
